[a-general]
home = "gemini://gemini.circumlunar.space"
auto_redirect = false
http = 'default'
search = "gemini://gus.guru/search"
color = true
ansi = true
bullets = true
show_link = false
left_margin = 0.05
max_width = 80
downloads = ''
page_max_size = 2097152  # 2 MiB
page_max_time = 10
emoji_favicons = false
scrollbar = "auto"


[auth]
[auth.certs]
[auth.keys]

[keybindings]
# If you have a non-US keyboard, use bind_tab1 through bind_tab0 to
# setup the shift-number bindings: Eg, for US keyboards (the default):
bind_tab1 = "F1"
bind_tab2 = "F2"
bind_tab3 = "F3"
bind_tab4 = "F4"
bind_tab5 = "F5"
bind_tab6 = "F6"
bind_tab7 = "F7"
bind_tab8 = "F8"
bind_tab9 = "F9"
bind_tab0 = "F10"

# bind_link1 = "1"
# bind_link2 = "2"
# bind_link3 = "3"
# bind_link4 = "4"
# bind_link5 = "5"
# bind_link6 = "6"
# bind_link7 = "7"
# bind_link8 = "8"
# bind_link9 = "9"
# bind_link0 = "0"

# bind_bottom
# bind_edit
# bind_home
bind_bookmarks = "b"
bind_add_bookmark = "B"
# bind_save
bind_reload = "r"
bind_back = "h"
bind_pgdn = "t"
bind_pgup = "n"
bind_forward = "s"
bind_prev_tab = "H"
bind_next_tab = "S"
bind_new_tab = "c"
bind_close_tab = "q"
bind_quit = "Q"
# bind_help
bind_sub = "f"
# bind_add_sub

[url-handlers]
# ftp = 'filezilla'
other = 'off'


[[mediatype-handlers]]
cmd = ['feh', '--image-bg', 'black', '--draw-exif', '--scale-down', '-']
types = ["image"]
# no_prompt = true

[[mediatype-handlers]]
cmd = ['mpv', '-']
types = ["audio", "video"]

[cache]
max_size = 0  # Size in bytes
max_pages = 30 # The maximum number of pages the cache will store
timeout = 1800 # 30 mins

[proxies]
# gopher = "example.com:123"


[subscriptions]
popup = true
update_interval = 0 # disabled
workers = 3
entries_per_page = 20

[theme]
bg = "#2b2b2b" # background
fg = "#a9b7c6" # foreground

#dl = "#6b5070" # dark magenta
#btn = "#6b5070" # dark magenta
#bkmk = "#6b5070" # dark magenta
#modal = "#6b5070" # dark magenta

# EXAMPLES:
hdg_1 = "#629755" # dark green
hdg_2 = "#a6c255" # bright green
hdg_3 = "#a6c255" # bright green

tab_num = "#444440" # bright black
tab_divider = "#444440" # bright black
bottombar_label = "#a9b7c6" # foreground
bottombar_text = "#a9b7c6" # foreground
bottombar_bg = "#444440" # bright black
scrollbar = "#444440" # bright black

amfora_link = "#7ca8c6" # bright cyan
foreign_link = "#c03030" # dark red
link_number = "#808890" # dark white
regular_text = "#a9b7c6" # foreground
list_text = "#a9b7c6" # foreground
quote_text = "#a8a878" # dark yellow
preformatted_text = "#a8a878" # dark yellow

btn_bg  = "#2b2b2b" # background
btn_txt = "#a9b7c6" # foreground

dl_choice_modal_bg = "#3c4c62" # dark blue
dl_choice_modal_text = "#a9b7c6" # foreground
dl_modal_bg = "#3c4c62" # dark blue
dl_modal_text = "#a9b7c6" # foreground
info_modal_bg = "#3c4c62" # dark blue
info_modal_text = "#a9b7c6" # foreground
error_modal_bg = "#3c4c62" # dark blue
error_modal_text = "#a9b7c6" # foreground
yesno_modal_bg = "#3c4c62" # dark blue
yesno_modal_text = "#a9b7c6" # foreground
tofu_modal_bg = "#3c4c62" # dark blue
tofu_modal_text = "#a9b7c6" # foreground
subscription_modal_bg = "#3c4c62" # dark blue
subscription_modal_text = "#a9b7c6" # foreground

input_modal_bg = "#3c4c62" # dark blue
input_modal_text = "#a9b7c6" # foreground
input_modal_field_bg = "#2b2b2b" # background
input_modal_field_text = "#a9b7c6" # foreground

# bkmk_modal_bg
# bkmk_modal_text
# bkmk_modal_label
# bkmk_modal_field_bg
# bkmk_modal_field_text
