set $m_menu   "menu"
set $m_launch "launch"
set $m_system "session"
set $m_resize "rotate & resize"

bindsym $mod+Tab mode $m_menu
bindsym $mod+u   mode $m_resize

mode $m_menu {

  bindsym l mode $m_launch
  bindsym s mode $m_system
  bindsym r mode $m_resize

  bindsym Return mode default
  bindsym Escape mode default
}

mode $m_launch {

  bindsym b mode default ; $exec firefox
  bindsym c mode default ; workspace "10"; $exec chromium --ozone-platform-hint=auto --enable=WebRTCPipeWireCapturer --user-data-dir=/home/jktr/.config/chromium-element --app=https://element.0x16.de
  bindsym m mode default ; $exec_term ncmpcpp
  bindsym p mode default ; workspace "12"; $exec_term mutt

  bindsym Alt+m mode default   ; $exec_term ncmpcpp --host mpd
  bindsym Ctrl+m mode default ; $exec_term pulsemixer
  bindsym Shift+b mode default ; $exec chromium

  bindsym Return mode $m_menu
  bindsym Escape mode default
}

mode $m_system {

  bindsym c mode default ; reload
  bindsym h mode default ; $exec_term htop
  bindsym k mode default ; kill
  bindsym l mode default ; $exec swaylock
  bindsym s mode default ; $exec sh -c "swaylock --daemonize && systemctl suspend"

  bindsym Return mode $m_menu
  bindsym Escape mode default
}

set $resize_s  1
set $resize_m 10
mode $m_resize {

  # medium resize
  bindsym h resize grow   width  $resize_m px or $resize_m ppt
  bindsym t resize grow   height $resize_m px or $resize_m ppt
  bindsym n resize shrink height $resize_m px or $resize_m ppt
  bindsym s resize shrink width  $resize_m px or $resize_m ppt

  # small resize with Shift
  bindsym Shift+h resize grow   width  $resize_s px or $resize_s ppt
  bindsym Shift+t resize grow   height $resize_s px or $resize_s ppt
  bindsym Shift+n resize shrink height $resize_s px or $resize_s ppt
  bindsym Shift+s resize shrink width  $resize_s px or $resize_s ppt

  # rotate
  bindsym Ctrl+h mode default ; output "*" transform    270
  bindsym Ctrl+t mode default ; output "*" transform    180
  bindsym Ctrl+n mode default ; output "*" transform normal
  bindsym Ctrl+s mode default ; output "*" transform     90

  bindsym Return mode default
  bindsym Escape mode default
}

bindsym $mod+r      $exec makoctl dismiss
bindsym $mod+Ctrl+r $exec makoctl menu dmenu
bindsym $mod+Alt+r  $exec makoctl restore
