#!/bin/bash

# gen-colormap
# derives a setvtrgb(8)-compatible colormap from X11/Xresources

readonly xresources=${1:-../X11/Xresources}
readonly rgb_colors="$(grep "*color[0-9]" "$xresources"|cut -dr -f2-|sort -n|cut -d# -f2)"

for channel in {1..3}; do # RGB
    selector="$(( ${channel}*2-1))-$(( ${channel}*2 ))"
    cut -c"$selector" <<<"${rgb_colors}"|xargs -IXX printf '%d,' 0xXX|cut -d',' -f1-16
done
